$servicesToDisable = @(
    "BthHFSrv",
    "bthserv",
    "Browser",
    "MapsBroker",
    "lfsv",
    "HomeGroupListener",
    "HomeGroupProvider",
    "IISADMIN",
    "irmon",
    "ICS",
    "lltdsvc",
    "LxssManager",
    "FTPSVC",
    "MSiSCSI",
    "PNRPsvc",
    "p2psvc",
    "p2pimsvc",
    "PNRPAutoReg",
    "wercplsupport",
    "RasAuto",
    "SessionEnv",
    "TermService",
    "UmRdpService",
    "RPC",
    "RpcLocator",
    "RemoteRegistry",
    "RemoteAccess",
    "LanmanServer",
    "simptcp",
    "SNMP",
    "SSDPSRV",
    "upnphost",
    "WMSvc",
    "WerSvc",
    "WMPNetworkSvc",
    "icssvc",
    "WpnService",
    "PushToInstall",
    "WinRM",
    "InstallService",
    "W3SVC",
    "XboxGipSvc",
    "xbgm",
    "XblAuthManager",
    "XblGameSave",
    "XboxNetApiSvc"
)

foreach($service in $servicesToDisable){
    Stop-Service -Name $service -ErrorAction SilentlyContinue
    Set-Service -Name $service -StartupType Disabled
}